### ISSUE TITLE
Version 0.4.5 throws error when creating a forest

### ISSUE THREAD

**Issue by moleculezz** [TAMUArch/cookbook.windows_ad#78]
I don't know if this is the right location for this project. It's not very clear from the supermarket page. Normally there is a link to the github repo.

Today berkshelf updated this cookbook to version 0.4.5 and I get the following error:

```
Install-ADDSForest : Verification of prerequisites for Domain Controller promotion failed. The NetBIOS domain name may not contain periods.
```

Command executed

```
Install-ADDSForest -DomainName example.com -SafeModeAdministratorPassword (convertto-secures
tring 'Password' -asplaintext -Force) -DomainNetbiosName example.com -Force:$true
```

I checked the downloaded cookbook and in `providers/domain.rb` at line 40 I see this: 
`cmd << " -DomainNetbiosName #{new_resource.name}"`

But when I check this github repo. That line does not exist.
Where is this cookbook version being downloaded from?

**Comment by derekgroh** [comment]
@moleculezz I released 0.5.0 this morning can you check what version your metadata file says again?

**Comment by moleculezz** [comment]
@derekgroh I'm on the supermarket page. It only lists version 0.4.4 and 0.4.5 available. Perhaps you forgot to push it to supermarket? (I have no idea how supermarket works)

**Comment by derekgroh** [comment]
@moleculezz Indeed, well let me look into that.

0.4.5 is being pulled from supermarket, as are all things Berkshelf

For the error above, it seems like the domain name and the domainnetbiosname are the same variable, when the domainnetbiosname for 0.4.5 should be stated using options
options ({
  "domainnetbiosname" => "example.com"
})

**Comment by moleculezz** [comment]
@derekgroh Yeah. The problem is that there is a line in there that hardcodes the netbios name
```
if node['os_version'] >= '6.2'
      cmd = create_command
      cmd << " -DomainName #{new_resource.name}"
      cmd << " -SafeModeAdministratorPassword (convertto-securestring '#{new_resource.safe_mode_pass}' -asplaintext -Force)"
      cmd << " -DomainNetbiosName #{new_resource.name}"
      cmd << ' -Force:$true'
    else node['os_version'] <= '6.1'
```

**Comment by derekgroh** [comment]
@moleculezz There's some cleanup I'm going to have to do with my last merge to 0.5.0.  Tracing through the commits, it seems like domainnetbiosname was removed and is intended for the options.

To make the code work as is with 0.4.5, I'd suggest changing 
`
cmd << " -DomainNetbiosName #{new_resource.name}" to cmd << " -DomainNetbiosName #{new_resource.netbios_name}"
`

Add this to resources\domain.rb
`
attribute :netbios_name, kind_of: String
`

**Comment by moleculezz** [comment]
@derekgroh I wen't as far as v0.3.0 by checking out the git tags and that line doesn't seem to exist in none of the versions previous to 0.4.5. And master branch neither. So I don't really understand where it has been reintroduced.

**Comment by derekgroh** [comment]
@moleculezz pushed 0.4.5 tag from my workstation as well as a pre-release of 0.5.0.  

Looking back over the netbios issue, the command is different for 2008r2 and 2012, which isn't too difficult to address, however the different type create_commands do not all support the option for 2012.  This is rather difficult to code around at this time, but I'm open to exploring it next.

I brought up an issue like this a while back, but am unable to locate it, so I extend the question to you:

How do you feel it is best to address different command options between 2008 and 2012 as well as any powershell command differences?

**Comment by moleculezz** [comment]
@derekgroh I am using it for a 2012r2 server. As I suspected the 0.4.5 tag release is different from the supermarket 0.4.5 release. Mainly the `DomainNetbiosName` is present in the supermarket release and not in the github tag release.

Perhaps it's an idea to separate the various types of domain installs. Maybe something similar to how the [docker cookbook](https://github.com/chef-cookbooks/docker) does the different kinds of `docker_installation` resources?
Mind you, I'm no expert in this field and am not well versed in ruby/chef.

**Comment by derekgroh** [comment]
@moleculezz That's my fault then, it was probably in a test branch that I merged accidentally to get some other cookbook to work, but never removed it as I switched to options to pass the value into the provider. 

I'll consider this a feature request, but feel free to take a stab at it if you would like, best way to learn is to do.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
